name: "GNN4ITk_MM_Infer"
backend: "python"
platform: "python"

input [
  {
    name: "FEATURES_HITS"
    data_type: TYPE_FP64
    dims: [-1, 20]
  },
  {
    name: "FEATURES_PARTICLES"
    data_type: TYPE_FP64
    dims: [-1, 15]
  }
]

output [
  {
    name: "HIT_IDs"
    data_type: TYPE_INT32
    dims: [-1]
  },
  {
    name: "TRACK_IDs"
    data_type: TYPE_INT32
    dims: [-1]
  }
]

parameters: {
  key: "mm_batch_size"
  value: {
    string_value: "2000000"
  }
}

instance_group [
  {
    kind: KIND_GPU
  }
]

max_batch_size: 0